// Downloads the three families into public/fonts and regenerates app/fonts.css.
// The app has to render with no network and under a strict CSP, so nothing is
// fetched from Google at runtime.
// Run from frontend/: node scripts/fetch-fonts.mjs
import { mkdirSync, rmSync, writeFileSync } from "node:fs";

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

// Polish needs latin-ext. Greek was here for the Greek spelling of the product
// name, which no screen ever rendered, so it went with Literata.
const SUBSETS = new Set(["latin", "latin-ext"]);

// Marcellus is one static weight by design, so the headline steps ask for 400
// and never for bold: there is no 600 cut to load, only a synthesised one.
// Geist and Martian Mono are variable, one file per subset covering every weight.
const FAMILIES = [
  ["marcellus", "Marcellus"],
  ["geist", "Geist:wght@100..900"],
  ["martian-mono", "Martian+Mono:wght@400..500"],
];

// The generated CSS is the only index of what belongs here, so a family that
// leaves the list must not leave its files behind.
rmSync("public/fonts", { recursive: true, force: true });

mkdirSync("public/fonts", { recursive: true });
mkdirSync("app", { recursive: true });

const faces = [];

for (const [slug, query] of FAMILIES) {
  const res = await fetch(`https://fonts.googleapis.com/css2?family=${query}&display=block`, {
    headers: { "User-Agent": UA },
  });
  if (!res.ok) throw new Error(`Google Fonts answered ${res.status} for ${slug}`);
  const css = await res.text();

  // Each @font-face is preceded by a /* subset */ comment, which is the only
  // place the subset name appears.
  for (const block of css.split("/*").slice(1)) {
    const subset = block.slice(0, block.indexOf("*/")).trim();
    if (!SUBSETS.has(subset)) continue;

    const url = /src:\s*url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1].trim();
    const family = /font-family:\s*['"]([^'"]+)['"]/.exec(block)?.[1];
    const weight = /font-weight:\s*([^;]+);/.exec(block)?.[1].trim() ?? "400";
    if (!url || !range || !family) continue;

    const file = `${slug}-${subset}.woff2`;
    const body = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
    writeFileSync(`public/fonts/${file}`, body);
    faces.push({ family, weight, range, file });
    console.log(`${file.padEnd(32)} ${(body.length / 1024).toFixed(1)} kB  weight ${weight}`);
  }
}

if (!faces.length) throw new Error("no faces downloaded, the CSS shape must have changed");

const blocks = faces.map(
  (f) => `@font-face {
  font-family: "${f.family}";
  font-style: normal;
  font-weight: ${f.weight};
  font-display: block;
  src: url("/fonts/${f.file}") format("woff2");
  unicode-range: ${f.range};
}`,
);

writeFileSync(
  "app/fonts.css",
  `/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand.\n   Bundled locally because the app must render offline and under a strict CSP. */\n\n${blocks.join("\n\n")}\n`,
  "utf8",
);

console.log(`\napp/fonts.css: ${faces.length} faces`);
